classfier_list:
- model_name: "SVM"
  tokenizer_name: "TfidfVectorizer"
  split_size:
    train_size: 0.7
    test_size: 0.15
    valid_size: 0.15
  classfier_type: "sklearn"
  pipeline:
  - "TfidfVectorizer":
      encoding: "utf-8"
  - "SVM":
      gamma: "auto"
- model_name: "bert"
  tokenizer_name: "bert"
  split_size:
    train_size: 0.7
    test_size: 0.15
    valid_size: 0.15
  classfier_type: "huggingface"
  train_args:
    epochs: 3
    learning_rate: 2e-5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 64
    warmup_steps: 500
    weight_decay: 0.01
    logging_dir: "./logs"
    logging_steps: 10
    evaluation_strategy: "steps"
    save_strategy: "steps"
    save_steps: 10
    eval_steps: 10
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true
    report_to: "tensorboard"
  tokenizer_config:
    max_length: 512
    padding: "max_length"
    truncation: true
    return_tensors: "pt"
