"connection_string": "mongodb+srv://haowei:wang.6583510@haowei.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000" # Please provide your connection string here
"database_name": "everyai"
